ads/urls.py
from django.urls import path
from .import views
app_name = 'ads'
urlpatterns = [
     path('', views.index, name='index'),
     path('ad/', views.ads, name='ad'),
     path('ad/<int:ad_id>/', views.ad, name='ads'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
]

ads/models.py
from django.db import models
from django.utils import timezone

class AdTitle(models.Model):
    text = models.CharField(max_length=200)

    def __str__(self):
         return self.text
     
class Ad(models.Model):
    title = models.ForeignKey(AdTitle, on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Описання')
    price = models.CharField(max_length=200, verbose_name='Ціна')
    image = models.ImageField(upload_to='ads/%Y/%m/%d', blank=True)
    pub_date = models.DateTimeField(default=timezone.now, verbose_name='Дата публікації')
    STATUS_CHOICES = [
        ('active', 'Активно'),
        ('sold', 'Продано'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name='Статус')

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
         return f"{self.description[:50]}..."

ads/views.py
from django.shortcuts import render
from .models import AdTitle

def index(request):
     return render(request, 'ads/index.html')

def ads(request):
    ads = AdTitle.objects.order_by()
    return render(request, 'ads/ad.html', {'ads': ads})

def ad(request, ad_id):
     ad = AdTitle.objects.get(id=ad_id)
     entries = ad.ad_set.order_by()
     context = {'ad': ad, 'entries': entries}
     return render(request, 'ads/ads.html', context)

templates/ads/ad.html
{% extends 'ads/base.html' %}

{% block content %}
    <p>Каталоги</p>
    <ul>
        {% for ad in ads %}
            <li><a href="{% url 'ads:ads' ad.id %}"> {{ ad }}</a></li>
        {% empty %}
            <li> Немає каталогів </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/ads/ads.html
{% extends 'ads/base.html' %}
{% load static %}

{% block content %}
    <h1>Розділ: {{ ad }}</h1>
    <ul>
        {% for ad in entries %}
        <h1>{{ ad.title }}</h1>
        <p><strong>Цена:</strong> {{ ad.price }} руб.</p>
        <p><strong>Статус:</strong> {{ ad.get_status_display }}</p>
        <p><strong>Описание:</strong> {{ ad.description }}</p>
        <p><strong>Дата публикации:</strong> {{ ad.pub_date }}</p>
        <p>{{ ad.image }}</p>
        {% empty %}
            <li>Тут ще нічого не має</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/ads/base.html
<p>
    <a href="{% url 'ads:index' %}">Main</a> -
    <a href="{% url 'ads:ad' %}">Ad</a>
    </p>
    {% block content %} {% endblock content %}

templates/ads/index.html
{% extends "ads/base.html" %}

{% block content %}
     <p>Learning Log helps you keep track of your learning for any topic you're learning about.</p>
{% endblock content %}